name: Renovate Shared Workflow

on:
  workflow_call:
    inputs:
      renovate_config:
        description: "Path to the Renovate configuration file"
        required: true
        type: string
      renovate_token:
        description: "GitHub token for Renovate"
        required: true
        type: string

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.7
        with:
          configurationFile: ${{ inputs.renovate_config }}
          renovate_token: ${{ secrets.renovate_token }}
        env:
          LOG_LEVEL: debug
