name: Renovate Shared Workflow
on:
  workflow_call:
    inputs:
      renovate_config:
        description: "Path to config file"
        required: true
        type: string
    secrets:
      RENOVATE_TOKEN:
        required: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v41.0.7
        with:
          configurationFile: ${{ inputs.renovate_config }}
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
