name: Renovate Shared Workflow
on:
  workflow_call:
    inputs:
      renovate_config:
        description: "Path to config file"
        required: true
        type: string
      env:
        RENOVATE_TOKEN: ${{ vars.RENOVATE_TOKEN }}

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v41.0.7
        env:
          RENOVATE_TOKEN: ${{ env.RENOVATE_TOKEN }}
          LOG_LEVEL: debug
        with:
          configurationFile: ${{ inputs.renovate_config }}
